### ISSUE TITLE
factorize env in github actions

### ISSUE THREAD

**Issue by thuguerre** [thuguerre/bets-helper#70]
```
env:
          SA_PROJECT_ID: ${{ secrets.SA_PROJECT_ID }}
          SA_PRIVATE_KEY_ID: ${{ secrets.SA_PRIVATE_KEY_ID }}
          SA_PRIVATE_KEY: ${{ secrets.SA_PRIVATE_KEY }}
          SA_CLIENT_EMAIL: ${{ secrets.SA_CLIENT_EMAIL }}
          SA_CLIENT_ID: ${{ secrets.SA_CLIENT_ID }}
          SA_CLIENT_X509_CERT_URL: ${{ secrets.SA_CLIENT_X509_CERT_URL }}
          MONGODB_USER: ${{ secrets.MONGODB_USER }}
          MONGODB_PWD: ${{ secrets.MONGODB_PWD }}
          MONGODB_NAME: ${{ secrets.MONGODB_NAME }}
```

in `Get-Japan-Baseball-Odds.yml` and `Get-Japan-Baseball-Results.yml` .
